- bundle-generation/MCEconfig.yaml
- bundle-generation/MCHconfig.yaml
- bundle-generation/chart-templates/Chart.yaml
- bundle-generation/chart-templates/templates/clusterrole.yaml
- bundle-generation/chart-templates/templates/clusterrolebinding.yaml
- bundle-generation/chart-templates/templates/deployment.yaml
- bundle-generation/chart-templates/templates/deploymentspec.yaml
- bundle-generation/chart-templates/templates/role.yaml
- bundle-generation/chart-templates/templates/rolebinding.yaml
- bundle-generation/chart-templates/templates/serviceaccount.yaml
- bundle-generation/chart-templates/values.yaml
- bundle-generation/chart-values/managed-serviceaccount/values.yaml
- bundle-generation/generate-bundles.py
- bundle-generation/validate_csv.py
https://issues.redhat.com/browse/ACM-8475
I have moved the main bundle generation functionality to this repo, where it will be used by a wrapper script within the MCH and MCE repos
> adding mce generation

- bundle-generation/MCEconfig.yaml
> hive version

- bundle-generation/generate-bundles.py
Related Jira: https://issues.redhat.com/browse/ACM-10099.
> [ACM-10099] Added preserve_file logic to bundle automation

- bundle-generation/generate-bundles.py
> Set bundle automation automountServiceAccountToken to false

- bundle-generation/generate-bundles.py
Removing this logic to re-evaluate at a later time. This is currently breaking our builds for ACM 2.11 / MCE 2.6
> Removed automountServiceAccountToken logic

- bundle-generation/generate-sha-commits.py
Added support for Personal Access Token (PAT) for the regenerate sha commit script. When pulling from a private  repository, you need to provide a token for the github action to clone the private repository.
Added `env` for `GH_READ_PAT` for `regenerate-sha-commit` script.
> Added PAT support for regenerate-sha-commit script

- bundle-generation/generate-charts.py
Cherrypick https://github.com/stolostron/backplane-operator/pull/747
https://issues.redhat.com/browse/ACM-12987
> Inject annotations for deployments in addonTemplates

- bundle-generation/generate-sha-commits.py
> Update sha generate script

- bundle-generation/bundles-to-charts.py
Updating the bundle-automation to set deployment replicaCounts based on the `availabilityConfig`setting defined in MCH and MCE.
https://issues.redhat.com/browse/ACM-14424
Added overrides for replicaCount.
> [ACM-14424] Added deployment replicas override to bundle-automation

- bundle-generation/bundles-to-charts.py
Reverts stolostron/installer-dev-tools#29
> Revert "[ACM-14424] Added deployment replicas override to bundle-automation"

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
Added replica count override to bundle-automation. This will ensure that components can scale based on the availability config option that is defined in ACM 2.13 / MCE 2.8. This PR will also add version compatibility logic to ensure that changes are only added to specific release branches.
https://issues.redhat.com/browse/ACM-10883
Updated the `bundles-to-charts.py` and `generate-charts.py` script to add replica counts overrides to the component deployment spec field.
/cc @cameronmwall …
> [ACM-10883] Added replicas override to bundle-automation

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
> [ACM-10883] Fixed version error in bundle scripts

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
Before we can begin implementing the replica count override, we need to reach out to individual teams and determine if their component should be scaled or not. This PR will temporarily disable the override until we are able to add a flag to determine if we should ignore or scale.
Commented out replica count overrides.
> Disabled availabilityConfig replica count override

- bundle-generation/generate-charts.py
- bundle-generation/generate-sha-commits.py
- bundle-generation/move-charts.py
> Added cleanup step to automation scripts

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
- bundle-generation/move-charts.py
> Updated chart automation to render templated charts

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
If a feature isn't ready or available for a specific release branch, our automation will fail if we keep targeting a branch that isn’t prepared for delivery. This PR sets the minimum required branch to version 9.9 to ensure that only ready features are delivered
> Updated minimum requirement for non-release ready features

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
Updated the `generate-charts` script to better support onboarding new components via helm charts.
https://issues.redhat.com/browse/ACM-13577
Updated `generate-charts.py` script.
/cc @cameronmwall
> [ACM-13577] Enhanced automation workflow in generate-charts script

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
During the release process, some components are built directly from the master or main branch; however, not all branches relying on master or main need specific overrides. This PR introduces an enforcer to manage overrides as needed.
Added `enforce_master_check` parameter to `is_version_compatible` func.
> Added enforcer for master/main branch compatibility check

- bundle-generation/generate-charts.py
Updated the `generate-charts` script to add overrides to generic kubernetes resources (i.e namespace overrides)
Updated `generate-charts.py` script to support non Deployment resource overrides.
/cc @cameronmwall
> Updated generate-charts script to support generic helm resources overrides

- bundle-generation/generate-charts.py
> Added version compatibility for helm resource overrides

- bundle-generation/generate-charts.py
> Flight control namespace fix

- bundle-generation/bundles-to-charts.py
- scripts/bundle-generation/bundles-to-charts.py
- scripts/release/onboard-new-components.py
> Add escaped variables to bundle automation

- .github/workflows/lint-py.yml
- .github/workflows/lint-shell.yml
- scripts/aks/create-aks.sh
- scripts/aks/delete-aks.sh
- scripts/compliance/pod-enforce.sh
- scripts/compliance/pod-linter.sh
- scripts/release/release-version.sh
Added linting workflow to ensure best practices for our dev tools automation.
> Added linting workflow for repo scripts

- bundle-generation/generate-charts.py
This fixes existing issues in the flight control injection
> flight control enhancement

- bundle-generation/bundles-to-charts.py
- scripts/bundle_generation/olm_bundles_to_helm_charts.py
Updated the `bundle-generation` automation to support parsing `webhookdefinitions` from component's OLM bundle CSV resource.
https://issues.redhat.com/browse/ACM-17894
Updated `bundle` automation to support `webhookdefinitions`.
> [ACM-17894] Added support for olm bundle webhookdefinitions in CSV resource

- .github/workflows/lint-py.yml
- .github/workflows/lint-shell.yml
The github action is being updated to a minimum required version.
Refs:
- https://issues.redhat.com/browse/ACM-18952
> Update github action to required level

- bundle-generation/generate-charts.py
> Chart values change

- bundle-generation/generate-charts.py
Updated the generate-charts script to support `imageOverrides` for `StatefulSet` and `Job` resources.
> Updated generate-charts to support imageoverrides for kube resources

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
Currently, we only support excluding specific overrides at a global level for operator bundles and charts being onboarded into ACM/MCE. This PR aims to enhance customization by allowing exclusions at a more granular, component-specific level rather than applying them globally.
https://issues.redhat.com/browse/ACM-18824
Updated bundles and chart automation to support `security-context-constraints` overrides.
> [ACM-18824] Added support for overriding security-context-constraints for operators/charts

- scripts/release/onboard-new-components.py
- scripts/utils/common.py
> Updated onboarding script prompts to support new customizations

- bundle-generation/bundles-to-charts.py
- bundle-generation/generate-charts.py
- bundle-generation/generate-sha-commits.py
- bundle-generation/move-charts.py
> Added support for single component run and custom config usage

- scripts/qe/.gitignore
- scripts/qe/pr-downstream-status.sh
⬢ [redhat] ❯ ./pr-downstream-status.sh https://github.com/stolostron/multiclusterhub-operator/pull/2317 https://github.com/stolostron/backplane-operator/pull/1518 https://github.com/stolostron/multicluster-observability-operator/pull/1867 https://github.com/flightctl/flightctl/pull/1173
🟩 stolostron/multiclusterhub-operator pull 2317 is in the downstream build
🟩 stolostron/backplane-operator pull 1518 is in the downstream build
🟩 stolostron/multicluster-observability-operator pull 1867 is in the downstream build
🟪 flightctl/flightctl pull 1173 has diverged from the downstream build
> Script for checking if an array of PRs have made it into the downstream build yet

- bundle-generation/generate-charts.py
> Edge management image 2.15
